# MD5: 15cee3ead49e1a6b09a291338637db36
CFG_FEATURE_DEBUG_PRINT_ADDRESS                 := FEATURE_ON
CFG_FEATURE_AT_NV_WRITE_SUPPORT                 := YES
CFG_FEATURE_READ_LOG_FILTER_CFG                 := YES
CFG_FEATURE_MEMCPY_REBOOT_CFG                   := FEATURE_ON
CFG_FEATURE_PHONE_ENG_AT_CMD                    := FEATURE_ON
