# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_SYNAPTICS_TS_KIT_3_0)  += synaptics/
obj-$(CONFIG_SAMSUNG_TS_KIT_3_0)  += samsung/
#ifeq ($(CONFIG_HUAWEI_TS_TEST_3_0),y)
#EXTRA_CFLAGS += -DHUAWEI_TOUCHSCREEN_TEST
#endif
#EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
